- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3, venv
    apt: 
      pkg:               #pacotes, libs
      - python3
      - virtualenv
      update_cache: yes  #pegar sempre a versão mais att
    become: yes          #rodar como superuser
	- name: Instalando dependencias com pip (Django e Django rest)
		pip: 
			virtualenv: /home/ubuntu/pasta/venv
			name:
				- django
				- djangorestframework
	- name: Ativando venv e Iniciando o projeto
		shell: '. /home/ubuntu/pasta/venv/bin/activate; django-admin startproject setup /home/ubuntu/pasta'
	- name: Alterando o hosts do settings
		lineinfile:
			path: /home/ubuntu/pasta/setup/settings.py
			regexp: 'ALLOWED_HOSTS'
			line: 'ALLOWED_HOSTS = ["*"]'
			backrefs: yes