- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3, venv
    apt: 
      pkg:               #pacotes, libs
      - python3
      - virtualenv
      update_cache: yes  #pegar sempre a versão mais att
    become: yes          #rodar como superuser