name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: luucasfer94
        password: ${{ secrets.DOCKER_HUB }}
             
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./alura-githubActions-Golang/Dockerfile
        push: true
        tags: luucasfer94/testeGo:1.0.0
